const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=1)=>Number(n).toFixed(d).replace('.',',');
function tab(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active-panel',x.id===id));$('#'+id)?.scrollIntoView({behavior:'smooth'});}$$('.tab').forEach(x=>x.onclick=()=>tab(x.dataset.tab));$$('[data-go]').forEach(x=>x.onclick=()=>tab(x.dataset.go));
function arrow(c,x1,y1,x2,y2,color='#2f9dc0',width=2.4){const a=Math.atan2(y2-y1,x2-x1),h=9;c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(x1,y1);c.lineTo(x2,y2);c.stroke();c.beginPath();c.moveTo(x2,y2);c.lineTo(x2-h*Math.cos(a-Math.PI/6),y2-h*Math.sin(a-Math.PI/6));c.moveTo(x2,y2);c.lineTo(x2-h*Math.cos(a+Math.PI/6),y2-h*Math.sin(a+Math.PI/6));c.stroke();}
function drawBarMagnet(c,x,y,w,h){c.fillStyle='#1687b7';c.fillRect(x,y,w/2,h);c.fillStyle='#e65349';c.fillRect(x+w/2,y,w/2,h);c.strokeStyle='#40555b';c.lineWidth=2;c.strokeRect(x,y,w,h);c.fillStyle='#fff';c.font='900 22px Segoe UI';c.textAlign='center';c.fillText('N',x+w*.25,y+h*.62);c.fillText('S',x+w*.75,y+h*.62);}

/* ВЕКТОР B */
const nx=$('#needleX'),ny=$('#needleY');function updateInduction(){$('#needleXOut').textContent=nx.value+' %';$('#needleYOut').textContent=ny.value+' %';}[nx,ny].forEach(x=>x.oninput=updateInduction);
function fieldAtPoint(px,py){const N={x:350,y:270},S={x:570,y:270};const dxN=px-N.x,dyN=py-N.y,rN2=dxN*dxN+dyN*dyN+800;const dxS=px-S.x,dyS=py-S.y,rS2=dxS*dxS+dyS*dyS+800;let bx=dxN/Math.pow(rN2,1.5)-dxS/Math.pow(rS2,1.5),by=dyN/Math.pow(rN2,1.5)-dyS/Math.pow(rS2,1.5);const m=Math.hypot(bx,by)||1;return {bx:bx/m,by:by/m,strength:Math.min(1,3500*(1/rN2+1/rS2))};}
function drawInduction(){const cn=$('#inductionCanvas'),c=cn.getContext('2d');c.clearRect(0,0,cn.width,cn.height);c.fillStyle='#fbfefe';c.fillRect(0,0,cn.width,cn.height);drawBarMagnet(c,350,235,220,70);c.strokeStyle='#62b8d3';c.lineWidth=2;for(let k=0;k<5;k++){const off=45+k*27;c.beginPath();c.moveTo(350,250);c.bezierCurveTo(200-off,120-off/3,720+off,120-off/3,570,250);c.stroke();c.beginPath();c.moveTo(350,290);c.bezierCurveTo(200-off,420+off/3,720+off,420+off/3,570,290);c.stroke();}const px=90+(+nx.value/100)*740,py=75+(+ny.value/100)*390,f=fieldAtPoint(px,py),ang=Math.atan2(f.by,f.bx),L=46;c.save();c.translate(px,py);c.rotate(ang);c.fillStyle='#1687b7';c.beginPath();c.moveTo(0,-8);c.lineTo(L,0);c.lineTo(0,8);c.closePath();c.fill();c.fillStyle='#e65349';c.beginPath();c.moveTo(0,-8);c.lineTo(-L,0);c.lineTo(0,8);c.closePath();c.fill();c.restore();arrow(c,px,py,px+f.bx*78,py+f.by*78,'#2f9dc0',3);c.fillStyle='#2f9dc0';c.font='900 16px Segoe UI';c.fillText('B',px+f.bx*92,py+f.by*92);$('#bStrengthText').textContent=f.strength>.55?'Поле тут сильніше — точка ближче до полюса.':f.strength>.25?'Поле середньої сили.':'Поле слабше далеко від полюсів.';}

/* ЛІНІЇ ПОЛЯ */
const ms=$('#magnetStrength'),fam=$('#fieldArrowMode');function updateFieldlines(){const s=+ms.value;$('#magnetStrengthOut').textContent=s+' %';$('#lineDensityBar').style.width=s+'%';$('#lineDensityText').textContent=s<35?'мала':s<70?'середня':'велика';}[ms,fam].forEach(x=>x.oninput=updateFieldlines);
function drawFieldlines(){const cn=$('#fieldlineCanvas'),c=cn.getContext('2d'),s=+ms.value/100,arrows=fam.value==='on';c.clearRect(0,0,cn.width,cn.height);c.fillStyle='#fbfefe';c.fillRect(0,0,cn.width,cn.height);drawBarMagnet(c,350,235,220,70);const n=4+Math.round(s*7);c.strokeStyle=`rgba(47,157,192,${.35+.55*s})`;c.lineWidth=1.2+2*s;for(let k=0;k<n;k++){const off=28+k*(115/Math.max(1,n-1));c.beginPath();c.moveTo(350,248);c.bezierCurveTo(260-off,150-off*.4,660+off,150-off*.4,570,248);c.stroke();c.beginPath();c.moveTo(350,292);c.bezierCurveTo(260-off,390+off*.4,660+off,390+off*.4,570,292);c.stroke();if(arrows&&k%2===0){arrow(c,420,145-off*.18,500,145-off*.18,'#2f9dc0',2.2);arrow(c,420,395+off*.18,500,395+off*.18,'#2f9dc0',2.2);}}if(arrows){arrow(c,530,270,390,270,'#2f9dc0',3);c.fillStyle='#355d66';c.font='800 13px Segoe UI';c.fillText('усередині: S → N',460,330);}c.fillStyle='#355d66';c.font='800 14px Segoe UI';c.fillText('зовні: N → S',460,78);}

/* ОДНОРІДНЕ ПОЛЕ */
const um=$('#uniformMode'),ub=$('#uniformB');function updateUniform(){const B=+ub.value;$('#uniformBOut').textContent=fmt(B,2)+' Тл';const txt={lines:'Лінії паралельні й розташовані на однаковій відстані.',out:'Точки ⊙ означають: B напрямлений із площини рисунка до нас.',in:'Хрестики ⊗ означають: B напрямлений у площину рисунка від нас.',gap:'У центральній області між різнойменними полюсами поле близьке до однорідного.'};$('#uniformExplain').textContent=txt[um.value];}[um,ub].forEach(x=>x.oninput=updateUniform);
function drawUniform(){const cn=$('#uniformCanvas'),c=cn.getContext('2d'),mode=um.value,B=+ub.value;c.clearRect(0,0,cn.width,cn.height);c.fillStyle='#fbfefe';c.fillRect(0,0,cn.width,cn.height);const strength=(B-.1)/.9;if(mode==='lines'){const n=5+Math.round(strength*5);for(let i=0;i<n;i++){const y=85+i*(360/(n-1));arrow(c,120,y,800,y,'#2f9dc0',1.5+1.5*strength);}}else if(mode==='out'||mode==='in'){c.fillStyle='#2f9dc0';c.font=`900 ${22+8*strength}px Segoe UI`;c.textAlign='center';const n=5+Math.round(strength*4);for(let r=0;r<n;r++)for(let col=0;col<9;col++)c.fillText(mode==='out'?'⊙':'⊗',135+col*82,100+r*(350/(n-1)));}else{c.fillStyle='#e65349';c.fillRect(105,170,150,150);c.fillStyle='#1687b7';c.fillRect(665,170,150,150);c.fillStyle='#fff';c.font='900 30px Segoe UI';c.textAlign='center';c.fillText('S',180,258);c.fillText('N',740,258);const n=5+Math.round(strength*5);for(let i=0;i<n;i++){const y=145+i*(230/(n-1));arrow(c,645,y,275,y,'#2f9dc0',1.5+1.5*strength);}}}

/* ПОЛЕ ЗЕМЛІ */
const tilt=$('#axisTilt'),storm=$('#stormRange');function updateEarth(){const a=+tilt.value,s=+storm.value;$('#axisTiltOut').textContent=fmt(a,1)+'°';$('#stormOut').textContent=s+' %';$('#stormState').textContent=s<25?'спокійне':s<60?'збурене':'магнітна буря';$('#stormHint').textContent=s<25?'Невеликі природні зміни поля відбуваються постійно.':s<60?'Поле помітно змінюється.':'Сильне глобальне збурення магнітного поля.';}[tilt,storm].forEach(x=>x.oninput=updateEarth);
function drawEarth(t){const cn=$('#earthCanvas'),c=cn.getContext('2d'),a=+tilt.value*Math.PI/180,s=+storm.value/100;c.clearRect(0,0,cn.width,cn.height);c.fillStyle='#fbfefe';c.fillRect(0,0,cn.width,cn.height);const cx=460,cy=280,R=105;c.fillStyle='#7eb7d6';c.beginPath();c.arc(cx,cy,R,0,Math.PI*2);c.fill();c.fillStyle='#7da45a';c.beginPath();c.ellipse(cx-30,cy-15,42,20,-.3,0,Math.PI*2);c.fill();c.beginPath();c.ellipse(cx+35,cy+25,35,18,.5,0,Math.PI*2);c.fill();c.strokeStyle='#697d83';c.lineWidth=2;c.setLineDash([8,6]);c.beginPath();c.moveTo(cx,90);c.lineTo(cx,470);c.stroke();c.setLineDash([]);c.fillStyle='#697d83';c.font='700 13px Segoe UI';c.fillText('вісь обертання',cx+55,475);const dx=Math.sin(a)*180,dy=Math.cos(a)*180;c.strokeStyle='#b65349';c.lineWidth=3;c.beginPath();c.moveTo(cx-dx,cy+dy);c.lineTo(cx+dx,cy-dy);c.stroke();c.fillStyle='#b65349';c.fillText('магнітна вісь',cx+dx+55,cy-dy);const sx=cx+Math.sin(a)*80,sy=cy-Math.cos(a)*80,nx2=cx-Math.sin(a)*80,ny2=cy+Math.cos(a)*80;c.fillStyle='#e65349';c.fillRect(sx-18,sy-18,36,36);c.fillStyle='#fff';c.font='900 18px Segoe UI';c.textAlign='center';c.fillText('S',sx,sy+6);c.fillStyle='#1687b7';c.fillRect(nx2-18,ny2-18,36,36);c.fillStyle='#fff';c.fillText('N',nx2,ny2+6);c.fillStyle='#355d66';c.font='800 13px Segoe UI';c.fillText('географічна Північ',cx,135);c.fillText('географічний Південь',cx,435);const wobble=s*18*Math.sin(t/400);c.strokeStyle=`rgba(47,157,192,${.55+.3*(1-s)})`;c.lineWidth=2+s*1.5;for(let k=0;k<5;k++){const off=45+k*30+wobble*(k%2?1:-1);c.beginPath();c.moveTo(nx2,ny2);c.bezierCurveTo(cx-210-off,cy+160,cx-210-off,cy-160,sx,sy);c.stroke();c.beginPath();c.moveTo(nx2,ny2);c.bezierCurveTo(cx+210+off,cy+160,cx+210+off,cy-160,sx,sy);c.stroke();}c.fillStyle=s>.6?'#b65349':'#355d66';c.font='900 14px Segoe UI';c.fillText(s>.6?'МАГНІТНА БУРЯ: лінії поля збурені':'спрощена дипольна модель поля Землі',460,525);}

/* ТЕСТ */
const qs=[['Магнітна індукція B — це:',['скалярна величина','векторна величина','лише одиниця'],'b'],['Одиниця магнітної індукції в СІ:',['ампер','тесла','вольт'],'b'],['Напрям B визначають за напрямом:',['північного полюса стрілки','південного полюса','сили тяжіння'],'a'],['Зовні магніту лінії йдуть:',['S → N','N → S','без напряму'],'b'],['Магнітні лінії:',['перетинаються','замкнені','завжди прямі'],'b'],['Де поле сильніше?',['де лінії щільніші','де ліній менше','густина неважлива'],'a'],['Однорідне поле:',['B однаковий за модулем і напрямом','B змінюється','B=0'],'a'],['⊙ означає:',['вектор до нас','вектор від нас','нульове поле'],'a'],['Біля географічної Півночі Землі:',['північний магнітний полюс','південний магнітний полюс','немає полюса'],'b'],['Сильне збурення поля Землі:',['магнітна буря','точка Кюрі','електроліз'],'a']];
function build(){$('#quizBox').innerHTML=qs.map((q,i)=>`<article class="question"><p>${i+1}. ${q[0]}</p><div class="answers">${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${String.fromCharCode(97+j)}"> ${a}</label>`).join('')}</div></article>`).join('');}
$('#check').onclick=()=>{let s=0;qs.forEach((q,i)=>{const a=$(`input[name=q${i}]:checked`),card=$$('.question')[i],ok=a?.value===q[2];card.className='question '+(ok?'correct':'wrong');if(ok)s++;});$('#result').textContent=`Результат: ${s} / ${qs.length}`;$('#result').className=s>=8?'good':'bad';};$('#reset').onclick=()=>{build();$('#result').textContent='';};
function animate(t){drawInduction();drawFieldlines();drawUniform();drawEarth(t);requestAnimationFrame(animate);}build();updateInduction();updateFieldlines();updateUniform();updateEarth();requestAnimationFrame(animate);
