const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const fmt=(n,d=2)=>Number(n).toFixed(d).replace('.',',');
function tab(id){$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.panel').forEach(x=>x.classList.toggle('active-panel',x.id===id));$('#'+id)?.scrollIntoView({behavior:'smooth',block:'start'})}
$$('.tab').forEach(x=>x.addEventListener('click',()=>tab(x.dataset.tab)));$$('[data-go]').forEach(x=>x.addEventListener('click',()=>tab(x.dataset.go)));

let ratedPower=60,appliance='LED-лампа',counter=0,lastFrame=performance.now();
const u=$('#uRange'),hours=$('#timeRange'),tariff=$('#tariffRange'),powerSwitch=$('#powerSwitch');
$$('.appliance').forEach(button=>button.addEventListener('click',()=>{ratedPower=+button.dataset.power;appliance=button.dataset.name;$$('.appliance').forEach(x=>x.classList.toggle('active',x===button));updateEnergy()}));
function energyValues(){const U=+u.value,P=ratedPower,I=P/U,t=+hours.value,wh=P*t,kwh=wh/1000,J=P*t*3600,cost=kwh*(+tariff.value);return{U,P,I,t,kwh,J,cost}}
function updateEnergy(){const v=energyValues();$('#applianceName').textContent=appliance;$('#uOut').textContent=v.U+' В';$('#timeOut').textContent=fmt(v.t,1)+' год';$('#tariffOut').textContent=fmt(+tariff.value)+' грн/кВт·год';$('#powerValue').textContent=v.P+' Вт';$('#currentValue').textContent=fmt(v.I)+' А';$('#workValue').textContent=Math.round(v.J).toLocaleString('uk-UA')+' Дж';$('#energyValue').textContent=fmt(v.kwh,3)+' кВт·год';$('#costValue').textContent=fmt(v.cost)+' грн';$('#energyFormula').textContent=`A = Pt = ${v.P} Вт · ${Math.round(v.t*3600)} с = ${Math.round(v.J).toLocaleString('uk-UA')} Дж`;$('#switchText').textContent=powerSwitch.checked?'Увімкнено':'Вимкнено'}
[u,hours,tariff,powerSwitch].forEach(x=>x.addEventListener('input',updateEnergy));$('#resetEnergy').addEventListener('click',()=>{counter=0;$('#liveEnergy').textContent='0,0000 кВт·год'});
function line(ctx,x1,y1,x2,y2,color='#245865',w=6){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=w;ctx.lineCap='round';ctx.stroke()}
function drawEnergy(time){const c=$('#energyCanvas'),ctx=c.getContext('2d'),on=powerSwitch.checked,v=energyValues();ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fbfefe';ctx.fillRect(0,0,c.width,c.height);line(ctx,110,115,660,115);line(ctx,660,115,660,315);line(ctx,660,315,110,315);line(ctx,110,315,110,115);line(ctx,145,90,145,140,'#173f49',7);line(ctx,172,100,172,130,'#173f49',5);ctx.fillStyle='#d64e44';ctx.font='900 22px Segoe UI';ctx.fillText('+',138,75);ctx.fillText('−',166,160);ctx.fillStyle=on?'#ffe35b':'#edf2f3';ctx.strokeStyle='#26717d';ctx.lineWidth=5;ctx.beginPath();ctx.arc(660,215,43,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#173f49';ctx.font='800 16px Segoe UI';ctx.textAlign='center';ctx.fillText(appliance,660,220);ctx.fillStyle='#102c34';ctx.fillRect(300,290,190,50);ctx.fillStyle='#b9f3d6';ctx.font='700 17px Consolas';ctx.fillText(fmt(counter,4)+' kWh',395,331);ctx.fillStyle='#617a82';ctx.font='700 14px Segoe UI';ctx.fillText('Лічильник',395,365);if(on){ctx.setLineDash([11,15]);ctx.lineDashOffset=-(time/25);ctx.strokeStyle='#e64f42';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(180,115);ctx.lineTo(660,115);ctx.lineTo(660,315);ctx.lineTo(110,315);ctx.lineTo(110,115);ctx.lineTo(138,115);ctx.stroke();ctx.setLineDash([]);const glow=.5+.5*Math.sin(time/120);ctx.fillStyle=`rgba(255,207,40,${.12+glow*.18})`;ctx.beginPath();ctx.arc(660,215,62,0,Math.PI*2);ctx.fill()}}
function animateEnergy(time){const dt=Math.min(100,time-lastFrame);lastFrame=time;if(powerSwitch.checked){counter+=ratedPower/1000*dt/3600000*360;$('#liveEnergy').textContent=fmt(counter,4)+' кВт·год'}drawEnergy(time);drawHeat(time);requestAnimationFrame(animateEnergy)}

const iRange=$('#iRange'),rRange=$('#rRange'),heatTime=$('#heatTimeRange');
function heatValues(){const I=+iRange.value,R=+rRange.value,t=+heatTime.value,Q=I*I*R*t;return{I,R,t,Q}}
function updateHeat(){const v=heatValues();$('#iOut').textContent=fmt(v.I,1)+' А';$('#rOut').textContent=v.R+' Ом';$('#heatTimeOut').textContent=v.t+' с';$('#heatValue').textContent=Math.round(v.Q).toLocaleString('uk-UA')+' Дж';$('#heatFormula').textContent=`Q = ${fmt(v.I,1)}² · ${v.R} · ${v.t}`;const intensity=Math.min(100,10+Math.sqrt(v.Q/75000)*90);$('#heatBar').style.width=intensity+'%';$('#heatConclusion').innerHTML=v.Q>30000?'<b>Висновок:</b> провідник сильно нагрівається — за великих струмів потрібен захист від перегрівання.':'<b>Спостереження:</b> збільш силу струму вдвічі — кількість теплоти зросте в чотири рази.'}
[iRange,rRange,heatTime].forEach(x=>x.addEventListener('input',updateHeat));
function drawHeat(time){const c=$('#heatCanvas'),ctx=c.getContext('2d'),v=heatValues(),hot=Math.min(1,Math.sqrt(v.Q/75000));ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fbfefe';ctx.fillRect(0,0,c.width,c.height);line(ctx,90,215,235,215);line(ctx,525,215,675,215);ctx.strokeStyle=`rgb(${Math.round(35+210*hot)},${Math.round(105-55*hot)},${Math.round(125-85*hot)})`;ctx.lineWidth=12;ctx.beginPath();for(let x=235;x<=525;x+=4){const y=215+Math.sin((x-235)/13)*22;ctx.lineTo(x,y)}ctx.stroke();ctx.fillStyle='#173f49';ctx.font='800 18px Segoe UI';ctx.textAlign='center';ctx.fillText('Нагрівальний провідник',380,290);ctx.fillStyle='#667e85';ctx.font='15px Segoe UI';ctx.fillText(`I = ${fmt(v.I,1)} А   R = ${v.R} Ом   t = ${v.t} с`,380,330);if(hot>.2){for(let k=0;k<5;k++){ctx.strokeStyle=`rgba(230,79,55,${hot*.45})`;ctx.lineWidth=3;ctx.beginPath();const x=290+k*48,shift=Math.sin(time/300+k)*8;ctx.moveTo(x,170);ctx.bezierCurveTo(x-12+shift,145,x+12-shift,125,x,100);ctx.stroke()}}}

const questions=[['За якою формулою визначають роботу струму?',['A = UIt','A = UI/t','A = I/R'],'a'],['Одиниця потужності в SI:',['Джоуль','Ват','Кіловат-година'],'b'],['Чому дорівнює 1 кВт·год?',['3600 Дж','3,6·10⁶ Дж','1000 Дж'],'b'],['Формула закону Джоуля—Ленца:',['Q = I²Rt','Q = U/I','Q = Pt²'],'a'],['Як зміниться Q, якщо I збільшити вдвічі?',['Удвічі','Учетверо','Не зміниться'],'b'],['Що вимірює побутовий електролічильник?',['Силу струму','Опір','Роботу електричного струму'],'c']];
function buildQuiz(){$('#quizBox').innerHTML=questions.map((q,i)=>`<article class="question"><p>${i+1}. ${q[0]}</p><div class="answers">${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${String.fromCharCode(97+j)}"> ${a}</label>`).join('')}</div></article>`).join('')}
$('#checkQuiz').addEventListener('click',()=>{let score=0;questions.forEach((q,i)=>{const a=$(`input[name="q${i}"]:checked`),card=$$('.question')[i],ok=a?.value===q[2];card.className='question '+(ok?'correct':'wrong');if(ok)score++});const out=$('#quizResult');out.textContent=`Результат: ${score} / ${questions.length}`;out.className=score>=5?'good':'bad'});$('#resetQuiz').addEventListener('click',()=>{buildQuiz();$('#quizResult').textContent=''});
buildQuiz();updateEnergy();updateHeat();requestAnimationFrame(animateEnergy);

// Final drawing functions: source polarity is + on the right; the heating wire starts without a stray diagonal.
function drawEnergy(time){
  const c=$('#energyCanvas'),ctx=c.getContext('2d'),on=powerSwitch.checked;
  ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fbfefe';ctx.fillRect(0,0,c.width,c.height);
  line(ctx,110,115,660,115);line(ctx,660,115,660,315);line(ctx,660,315,110,315);line(ctx,110,315,110,115);
  line(ctx,145,100,145,130,'#173f49',5);line(ctx,172,90,172,140,'#173f49',7);
  ctx.fillStyle='#d64e44';ctx.font='900 22px Segoe UI';ctx.fillText('−',138,75);ctx.fillText('+',166,160);
  ctx.fillStyle=on?'#ffe35b':'#edf2f3';ctx.strokeStyle='#26717d';ctx.lineWidth=5;ctx.beginPath();ctx.arc(660,215,43,0,Math.PI*2);ctx.fill();ctx.stroke();
  ctx.fillStyle='#173f49';ctx.font='800 16px Segoe UI';ctx.textAlign='center';ctx.fillText(appliance,660,220);
  ctx.fillStyle='#102c34';ctx.fillRect(300,290,190,50);ctx.fillStyle='#b9f3d6';ctx.font='700 17px Consolas';ctx.fillText(fmt(counter,4)+' kWh',395,331);ctx.fillStyle='#617a82';ctx.font='700 14px Segoe UI';ctx.fillText('Лічильник',395,365);
  if(on){ctx.setLineDash([11,15]);ctx.lineDashOffset=-(time/25);ctx.strokeStyle='#e64f42';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(180,115);ctx.lineTo(660,115);ctx.lineTo(660,315);ctx.lineTo(110,315);ctx.lineTo(110,115);ctx.lineTo(138,115);ctx.stroke();ctx.setLineDash([]);const glow=.5+.5*Math.sin(time/120);ctx.fillStyle=`rgba(255,207,40,${.12+glow*.18})`;ctx.beginPath();ctx.arc(660,215,62,0,Math.PI*2);ctx.fill()}
}

function drawHeat(time){
  const c=$('#heatCanvas'),ctx=c.getContext('2d'),v=heatValues(),hot=Math.min(1,Math.sqrt(v.Q/75000));
  ctx.clearRect(0,0,c.width,c.height);ctx.fillStyle='#fbfefe';ctx.fillRect(0,0,c.width,c.height);line(ctx,90,215,235,215);line(ctx,525,215,675,215);
  ctx.strokeStyle=`rgb(${Math.round(35+210*hot)},${Math.round(105-55*hot)},${Math.round(125-85*hot)})`;ctx.lineWidth=12;ctx.beginPath();
  for(let x=235;x<=525;x+=4){const y=215+Math.sin((x-235)/13)*22;if(x===235)ctx.moveTo(x,y);else ctx.lineTo(x,y)}ctx.stroke();
  ctx.fillStyle='#173f49';ctx.font='800 18px Segoe UI';ctx.textAlign='center';ctx.fillText('Нагрівальний провідник',380,290);ctx.fillStyle='#667e85';ctx.font='15px Segoe UI';ctx.fillText(`I = ${fmt(v.I,1)} А   R = ${v.R} Ом   t = ${v.t} с`,380,330);
  if(hot>.2){for(let k=0;k<5;k++){ctx.strokeStyle=`rgba(230,79,55,${hot*.45})`;ctx.lineWidth=3;ctx.beginPath();const x=290+k*48,shift=Math.sin(time/300+k)*8;ctx.moveTo(x,170);ctx.bezierCurveTo(x-12+shift,145,x+12-shift,125,x,100);ctx.stroke()}}
}
